# Generated by Django 5.2.9 on 2025-12-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cooking_time', models.IntegerField()),
                ('difficulty', models.CharField(max_length=20)),
                ('ingredients', models.ManyToManyField(to='ingredients.ingredient')),
            ],
        ),
    ]
